version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - '5432:5432'
    networks:
      - app
    volumes:
      - ../postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: Asia/Seoul    # PostgreSQL의 타임존을 KST로 설정
      PGTZ: Asia/Seoul  # PostgreSQL 내부 타임존 설정
    restart: always
  
  pgexporter:
    image: wrouesnel/postgres_exporter
    container_name: pgexporter
    restart: always
    environment:
      DATA_SOURCE_NAME: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable"
    depends_on:
      - postgres
    networks:
      - app

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app
    volumes:
    - type: bind
      source: ../redis_data
      target: /data
      read_only: false
    command: [
      "redis-server",
      "--appendonly", "yes",
      "--notify-keyspace-events", "Ex",
      "--slave-read-only", "no"
    ]

networks:
  app:
    external: true
    name: app
