version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - '5432:5432'
    networks:
      - app
    volumes:
      - ../postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app
    volumes:
      - ../redis_data:/data # Redis 데이터가 저장될 경로를 볼륨에 매핑
    command: ["redis-server", "--appendonly", "yes"] # AOF 활성화 (데이터 복구를 위해)


networks:
  app:
    external: true
    name: app